localdb:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=onboard

testdb:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=test_onboard
